//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 
namespace BOLib
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    
    public partial class Company {
        
        private CompanyCompanyInfo companyInfoField;
        
        private CompanyPurchase purchaseField;
        
        private CompanySupply supplyField;
        
        private CompanyGLData gLDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanyCompanyInfo CompanyInfo {
            get {
                return this.companyInfoField;
            }
            set {
                this.companyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanyPurchase Purchase {
            get {
                return this.purchaseField;
            }
            set {
                this.purchaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanySupply Supply {
            get {
                return this.supplyField;
            }
            set {
                this.supplyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanyGLData GLData {
            get {
                return this.gLDataField;
            }
            set {
                this.gLDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    
    public partial class CompanyCompanyInfo {
        
        private string companyNameField;
        
        private string companyUENField;
        
        private string gSTNoField;
        
        private System.DateTime periodStartField;
        
        private System.DateTime periodEndField;
        
        private System.DateTime iAFCreationDateField;
        
        private string productVersionField;
        
        private string iAFVersionField;
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyUEN {
            get {
                return this.companyUENField;
            }
            set {
                this.companyUENField = value;
            }
        }
        
        /// <remarks/>
        public string GSTNo {
            get {
                return this.gSTNoField;
            }
            set {
                this.gSTNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PeriodStart {
            get {
                return this.periodStartField;
            }
            set {
                this.periodStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime PeriodEnd {
            get {
                return this.periodEndField;
            }
            set {
                this.periodEndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime IAFCreationDate {
            get {
                return this.iAFCreationDateField;
            }
            set {
                this.iAFCreationDateField = value;
            }
        }
        
        /// <remarks/>
        public string ProductVersion {
            get {
                return this.productVersionField;
            }
            set {
                this.productVersionField = value;
            }
        }
        
        /// <remarks/>
        public string IAFVersion {
            get {
                return this.iAFVersionField;
            }
            set {
                this.iAFVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   
    public partial class CompanyPurchase {
        
        private CompanyPurchasePurchaseLines[] purchaseLinesField;
        
        private decimal purchaseTotalSGDField;
        
        private decimal gSTTotalSGDField;
        
        private long transactionCountTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanyPurchasePurchaseLines[] PurchaseLines {
            get {
                return this.purchaseLinesField;
            }
            set {
                this.purchaseLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal PurchaseTotalSGD {
            get {
                return this.purchaseTotalSGDField;
            }
            set {
                this.purchaseTotalSGDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal GSTTotalSGD {
            get {
                return this.gSTTotalSGDField;
            }
            set {
                this.gSTTotalSGDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long TransactionCountTotal {
            get {
                return this.transactionCountTotalField;
            }
            set {
                this.transactionCountTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
   
    public partial class CompanyPurchasePurchaseLines {
        
        private string supplierNameField;
        
        private string supplierUENField;
        
        private System.DateTime invoiceDateField;
        
        private string invoiceNoField;
        
        private string permitNoField;
        
        private long lineNoField;
        
        private string productDescriptionField;
        
        private decimal purchaseValueSGDField;
        
        private decimal gSTValueSGDField;
        
        private string taxCodeField;
        
        private string fCYCodeField;
        
        private decimal purchaseFCYField;
        
        private decimal gSTFCYField;
        
        /// <remarks/>
        public string SupplierName {
            get {
                return this.supplierNameField;
            }
            set {
                this.supplierNameField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierUEN {
            get {
                return this.supplierUENField;
            }
            set {
                this.supplierUENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public string PermitNo {
            get {
                return this.permitNoField;
            }
            set {
                this.permitNoField = value;
            }
        }
        
        /// <remarks/>
        public long LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal PurchaseValueSGD {
            get {
                return this.purchaseValueSGDField;
            }
            set {
                this.purchaseValueSGDField = value;
            }
        }
        
        /// <remarks/>
        public decimal GSTValueSGD {
            get {
                return this.gSTValueSGDField;
            }
            set {
                this.gSTValueSGDField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        public string FCYCode {
            get {
                return this.fCYCodeField;
            }
            set {
                this.fCYCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal PurchaseFCY {
            get {
                return this.purchaseFCYField;
            }
            set {
                this.purchaseFCYField = value;
            }
        }
        
        /// <remarks/>
        public decimal GSTFCY {
            get {
                return this.gSTFCYField;
            }
            set {
                this.gSTFCYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CompanySupply {
        
        private CompanySupplySupplyLines[] supplyLinesField;
        
        private decimal supplyTotalSGDField;
        
        private decimal gSTTotalSGDField;
        
        private long transactionCountTotalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SupplyLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanySupplySupplyLines[] SupplyLines {
            get {
                return this.supplyLinesField;
            }
            set {
                this.supplyLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal SupplyTotalSGD {
            get {
                return this.supplyTotalSGDField;
            }
            set {
                this.supplyTotalSGDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal GSTTotalSGD {
            get {
                return this.gSTTotalSGDField;
            }
            set {
                this.gSTTotalSGDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long TransactionCountTotal {
            get {
                return this.transactionCountTotalField;
            }
            set {
                this.transactionCountTotalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CompanySupplySupplyLines {
        
        private string customerNameField;
        
        private string customerUENField;
        
        private System.DateTime invoiceDateField;
        
        private string invoiceNoField;
        
        private long lineNoField;
        
        private string productDescriptionField;
        
        private decimal supplyValueSGDField;
        
        private decimal gSTValueSGDField;
        
        private string taxCodeField;
        
        private string countryField;
        
        private string fCYCodeField;
        
        private decimal supplyFCYField;
        
        private decimal gSTFCYField;
        
        /// <remarks/>
        public string CustomerName {
            get {
                return this.customerNameField;
            }
            set {
                this.customerNameField = value;
            }
        }
        
        /// <remarks/>
        public string CustomerUEN {
            get {
                return this.customerUENField;
            }
            set {
                this.customerUENField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime InvoiceDate {
            get {
                return this.invoiceDateField;
            }
            set {
                this.invoiceDateField = value;
            }
        }
        
        /// <remarks/>
        public string InvoiceNo {
            get {
                return this.invoiceNoField;
            }
            set {
                this.invoiceNoField = value;
            }
        }
        
        /// <remarks/>
        public long LineNo {
            get {
                return this.lineNoField;
            }
            set {
                this.lineNoField = value;
            }
        }
        
        /// <remarks/>
        public string ProductDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public decimal SupplyValueSGD {
            get {
                return this.supplyValueSGDField;
            }
            set {
                this.supplyValueSGDField = value;
            }
        }
        
        /// <remarks/>
        public decimal GSTValueSGD {
            get {
                return this.gSTValueSGDField;
            }
            set {
                this.gSTValueSGDField = value;
            }
        }
        
        /// <remarks/>
        public string TaxCode {
            get {
                return this.taxCodeField;
            }
            set {
                this.taxCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string FCYCode {
            get {
                return this.fCYCodeField;
            }
            set {
                this.fCYCodeField = value;
            }
        }
        
        /// <remarks/>
        public decimal SupplyFCY {
            get {
                return this.supplyFCYField;
            }
            set {
                this.supplyFCYField = value;
            }
        }
        
        /// <remarks/>
        public decimal GSTFCY {
            get {
                return this.gSTFCYField;
            }
            set {
                this.gSTFCYField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class CompanyGLData {
        
        private CompanyGLDataGLDataLines[] gLDataLinesField;
        
        private decimal totalDebitField;
        
        private decimal totalCreditField;
        
        private long transactionCountTotalField;
        
        private string gLTCurrencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("GLDataLines", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public CompanyGLDataGLDataLines[] GLDataLines {
            get {
                return this.gLDataLinesField;
            }
            set {
                this.gLDataLinesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalDebit {
            get {
                return this.totalDebitField;
            }
            set {
                this.totalDebitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TotalCredit {
            get {
                return this.totalCreditField;
            }
            set {
                this.totalCreditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long TransactionCountTotal {
            get {
                return this.transactionCountTotalField;
            }
            set {
                this.transactionCountTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string GLTCurrency {
            get {
                return this.gLTCurrencyField;
            }
            set {
                this.gLTCurrencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    
    public partial class CompanyGLDataGLDataLines {
        
        private System.DateTime transactionDateField;
        
        private string accountIDField;
        
        private string accountNameField;
        
        private string transactionDescriptionField;
        
        private string nameField;
        
        private string transactionIDField;
        
        private string sourceDocumentIDField;
        
        private string sourceTypeField;
        
        private decimal debitField;
        
        private decimal creditField;
        
        private decimal balanceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime TransactionDate {
            get {
                return this.transactionDateField;
            }
            set {
                this.transactionDateField = value;
            }
        }
        
        /// <remarks/>
        public string AccountID {
            get {
                return this.accountIDField;
            }
            set {
                this.accountIDField = value;
            }
        }
        
        /// <remarks/>
        public string AccountName {
            get {
                return this.accountNameField;
            }
            set {
                this.accountNameField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionDescription {
            get {
                return this.transactionDescriptionField;
            }
            set {
                this.transactionDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string SourceDocumentID {
            get {
                return this.sourceDocumentIDField;
            }
            set {
                this.sourceDocumentIDField = value;
            }
        }
        
        /// <remarks/>
        public string SourceType {
            get {
                return this.sourceTypeField;
            }
            set {
                this.sourceTypeField = value;
            }
        }
        
        /// <remarks/>
        public decimal Debit {
            get {
                return this.debitField;
            }
            set {
                this.debitField = value;
            }
        }
        
        /// <remarks/>
        public decimal Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
            }
        }
        
        /// <remarks/>
        public decimal Balance {
            get {
                return this.balanceField;
            }
            set {
                this.balanceField = value;
            }
        }
    }
}
